name: CI

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build-and-test:
    name: ${{ matrix.os }} Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        # For more specific OS versions, you can specify them explicitly:
        # os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: "3.20.0"  # Specify the minimum version you need

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install -y ninja
          choco install -y visualstudio2022community --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.VC.CMake.Project"
        shell: pwsh

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build clang

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install ninja
          brew install llvm

      - name: Configure CMake
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            cmake -S . -B build -G "Visual Studio 17 2022" -A x64
          else
            cmake -S . -B build -G Ninja -DCMAKE_CXX_COMPILER=clang++
          fi

      - name: Build
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            cmake --build build --config Debug
          else
            cmake --build build
          fi

      - name: Run tests
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            ctest --test-dir build --output-on-failure --config Debug
          else
            ctest --test-dir build --output-on-failure
          fi
